package com.margelo.nitro.nitroblur

/**
 * Extension function to convert BlurTint enum (generated by Nitrogen) to an overlay color int.
 * Color values are based on Apple's iOS 14 Sketch Kit.
 *
 * Groups tint styles that share the same color base, then delegates to per-style
 * color calculations for unique styles.
 */
fun BlurTint.toOverlayColor(blurRadius: Double): Int {
  return when (this) {
    // Light group
    BlurTint.EXTRALIGHT,
    BlurTint.LIGHT,
    BlurTint.SYSTEMMATERIALLIGHT,
    BlurTint.SYSTEMULTRATHINMATERIALLIGHT,
    BlurTint.SYSTEMTHICKMATERIALLIGHT -> BlurTint.LIGHT.toColorInt(blurRadius)

    // Default group
    BlurTint.PROMINENT,
    BlurTint.DEFAULT,
    BlurTint.SYSTEMMATERIAL -> BlurTint.DEFAULT.toColorInt(blurRadius)

    // Dark group
    BlurTint.DARK,
    BlurTint.SYSTEMMATERIALDARK -> BlurTint.DARK.toColorInt(blurRadius)

    // Each has unique color mapping
    BlurTint.REGULAR,
    BlurTint.SYSTEMULTRATHINMATERIAL,
    BlurTint.SYSTEMTHICKMATERIAL,
    BlurTint.SYSTEMCHROMEMATERIAL,
    BlurTint.SYSTEMCHROMEMATERIALLIGHT,
    BlurTint.SYSTEMTHICKMATERIALDARK,
    BlurTint.SYSTEMTHINMATERIALLIGHT,
    BlurTint.SYSTEMTHINMATERIALDARK,
    BlurTint.SYSTEMULTRATHINMATERIALDARK,
    BlurTint.SYSTEMCHROMEMATERIALDARK,
    BlurTint.SYSTEMTHINMATERIAL -> this.toColorInt(blurRadius)
  }
}

/**
 * Per-style ARGB color calculation.
 * Color int represented by: a >> 24 + r >> 16 + g >> 8 + b
 * From Apple iOS 14 Sketch Kit - https://developer.apple.com/design/resources/
 */
private fun BlurTint.toColorInt(blurRadius: Double): Int {
  val intensity = blurRadius / 100.0
  return when (this) {
    BlurTint.DARK ->
      colorInt(25, 25, 25, intensity * 0.69)
    BlurTint.LIGHT ->
      colorInt(249, 249, 249, intensity * 0.78)
    BlurTint.REGULAR ->
      colorInt(179, 179, 179, intensity * 0.82)
    BlurTint.SYSTEMTHINMATERIALLIGHT ->
      colorInt(199, 199, 199, intensity * 0.78)
    BlurTint.SYSTEMTHINMATERIAL ->
      colorInt(199, 199, 199, intensity * 0.97)
    BlurTint.SYSTEMCHROMEMATERIAL ->
      colorInt(255, 255, 255, intensity * 0.75)
    BlurTint.SYSTEMCHROMEMATERIALLIGHT ->
      colorInt(255, 255, 255, intensity * 0.97)
    BlurTint.SYSTEMULTRATHINMATERIAL ->
      colorInt(191, 191, 191, intensity * 0.44)
    BlurTint.SYSTEMTHICKMATERIAL ->
      colorInt(153, 153, 153, intensity * 0.97)
    BlurTint.SYSTEMTHICKMATERIALDARK ->
      colorInt(37, 37, 37, intensity * 0.9)
    BlurTint.SYSTEMTHINMATERIALDARK ->
      colorInt(37, 37, 37, intensity * 0.7)
    BlurTint.SYSTEMULTRATHINMATERIALDARK ->
      colorInt(37, 37, 37, intensity * 0.55)
    BlurTint.SYSTEMCHROMEMATERIALDARK ->
      colorInt(0, 0, 0, intensity * 0.75)
    else ->
      colorInt(255, 255, 255, intensity * 0.44)
  }
}

private fun colorInt(r: Int, g: Int, b: Int, alpha: Double): Int {
  val a = (255 * alpha).toInt().coerceIn(0, 255)
  return (a shl 24) or (r shl 16) or (g shl 8) or b
}
